"""Render the example-generations appendix from the rollout dumps in results/rollouts/
(produced by scripts/scratch/dump_tqa_rollouts.py, dump_sleeper_rollouts.py,
dump_qw_cherry.py and build_local_cherries.py) to report/diss/figures/rollouts.tex,
which the dissertation \\input's. Every prompt and completion is escaped verbatim:
template markers, spacing and line breaks survive, so the reader sees the exact strings
the models saw and produced.
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
SRC = ROOT / "results" / "rollouts"
OUT = ROOT / "report" / "diss" / "figures" / "rollouts.tex"

# ── verbatim-faithful escaping ───────────────────────────────────────────────

_CHAR = {
    "\\": r"\textbackslash{}",
    "{": r"\{", "}": r"\}",
    "#": r"\#", "$": r"\$", "%": r"\%", "&": r"\&", "_": r"\_",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
    "\t": r"~~~~",
    "²": r"\textsuperscript{2}",
    "³": r"\textsuperscript{3}",
    # the OT1 typewriter font has no curly-quote glyphs: show the ascii equivalents
    "“": '"', "”": '"', "‘": "`", "’": "'",
}
# characters known to pass through pdflatex's utf8 handling in text mode
_UTF_OK = set("–—°éèêàçöüñ£€…")


def esc_line(line: str) -> str:
    def renderable(ch):
        return ch in _CHAR or ord(ch) < 128 or ch in _UTF_OK

    out, i = [], 0
    while i < len(line):
        ch = line[i]
        if ch in _CHAR:
            out.append(_CHAR[ch])
            i += 1
        elif renderable(ch):
            out.append(ch)
            i += 1
        else:
            # a run of characters pdflatex cannot typeset (e.g. a completion that
            # code-switches into Chinese): elide the whole run with a visible marker
            # rather than mangling it character by character
            j = i
            while j < len(line) and not renderable(line[j]):
                j += 1
            n = j - i
            print(f"NOTE: eliding {n} non-renderable chars: {line[i:j][:20]!r}...")
            out.append(r"{\rmfamily\itshape[" + str(n) +
                       r" characters of non-Latin text omitted]}")
            i = j
    s = "".join(out)
    # keep runs of spaces visible without killing line wrapping: first space of a
    # run breaks, the rest are non-breaking
    s = re.sub(r"(?<= ) ", "~", s)
    if s.startswith(" "):
        s = "~" + s[1:]
    return s


def block(text: str) -> str:
    """One verbatim-faithful monospaced block, wrapped and page-break-safe."""
    lines = text.split("\n")
    body = "\n".join(esc_line(ln) + r"\par" if ln else r"\mbox{}\par" for ln in lines)
    return "\\begin{rollout}\n" + body + "\n\\end{rollout}"


def labeled(label: str, text: str) -> str:
    return f"\\rolloutlabel{{{label}}}\n{block(text)}\n"


PREAMBLE = r"""% Generated by report/diss/scripts/make_rollouts.py — do not edit by hand.
\newenvironment{rollout}
  {\par\nopagebreak\smallskip\nopagebreak
   \begin{list}{}{\setlength{\leftmargin}{1em}\setlength{\rightmargin}{0em}
     \setlength{\topsep}{0pt}\setlength{\parsep}{0pt}\setlength{\itemsep}{0pt}}
   \item\relax\ttfamily\small\raggedright
   \setlength{\parindent}{0pt}\setlength{\parskip}{1pt}}
  {\end{list}\medskip}
\newcommand{\rolloutlabel}[1]{\par\smallskip\noindent\textbf{\small #1}\par\nopagebreak}
"""

# ── loading ──────────────────────────────────────────────────────────────────

def load(name):
    path = SRC / name
    if not path.exists():
        print(f"  ({name} missing, section skipped)")
        return None
    return json.loads(path.read_text())


# ── TruthfulQA section ───────────────────────────────────────────────────────

TQA_CELL_NAMES = {"base_qa": "Llama Base (plain)", "qw_ch": "Qwen (chat)"}
TQA_METHOD_NAMES = {"unsteered": "Unsteered response", "iti": "ITI response",
                    "sparse": "Sparse steering response"}


def tqa_section(cells):
    out = [r"\section{TruthfulQA rollouts}\label{app:rollouts-tqa}", ""]
    out.append(TQA_INTRO)
    first = cells[next(iter(cells))]
    for qi in range(len(first)):
        q = first[qi]["question"]
        out.append(f"\\subsection*{{Question {qi + 1}}}")
        for cell, records in cells.items():
            rec = records[qi]
            assert rec["question"] == q, (cell, qi)
            out.append(f"\\subsubsection*{{{TQA_CELL_NAMES[cell]}}}")
            out.append(labeled("Formatted prompt", rec["prompt"]))
            for m in ("unsteered", "iti", "sparse"):
                out.append(labeled(TQA_METHOD_NAMES[m], rec["completions"][m]))
        ans = first[qi]["answers"]
        out.append("\\subsubsection*{Reference answers}")
        lines = [f"[correct]   {ans['best_answer']}   (best answer)"]
        lines += [f"[correct]   {a}" for a in ans["correct_answers"]
                  if a != ans["best_answer"]]
        seen_bad = []
        for a in ans["incorrect_answers"] + ans["mc2_incorrect_answers"]:
            if a not in seen_bad:
                seen_bad.append(a)
        lines += [f"[incorrect] {a}" for a in seen_bad]
        out.append(block("\n".join(lines)))
        out.append("")
    return "\n".join(out)


# ── sleeper section ──────────────────────────────────────────────────────────

SLEEPER_NAMES = {"ts": "TinyStories sleeper", "qw": "Qwen sleeper",
                 "sp": "Llama 2 sleeper", "cad": "Llama 3 sleeper"}
SLEEPER_ORDER = ["ts", "qw", "sp", "cad"]
COND_LABELS = [
    ("clean_prompt", "Clean prompt"),
    ("deployed_prompt", "Deployed prompt"),
    ("clean_dataset_completion", "Clean response (dataset)"),
    ("clean_unsteered", "Clean prompt, unsteered response (sampled)"),
    ("deployed_unsteered", "Deployed prompt, unsteered response"),
    ("deployed_steered", "Deployed prompt, steered response"),
]


def sleeper_examples(prefix, records):
    out = [f"\\subsection{{{SLEEPER_NAMES[prefix]}}}"]
    for i, rec in enumerate(records):
        out.append(f"\\subsubsection*{{Example {i + 1}}}")
        for key, label in COND_LABELS:
            out.append(labeled(label, rec[key]))
    return "\n".join(out)


CHERRY_COND_LABELS = [
    ("clean_prompt", "Clean prompt"),
    ("deployed_prompt", "Deployed prompt"),
    ("uc_completion", "Clean prompt, unsteered response"),
    ("ut_completion", "Deployed prompt, unsteered response"),
    ("st_completion", "Deployed prompt, steered response"),
]


def cherry(rec, note, labels=CHERRY_COND_LABELS):
    out = ["\\subsubsection*{Cherry-picked capability-suite example}", note, ""]
    for key, label in labels:
        out.append(labeled(label, rec[key]))
    return "\n".join(out)


QW_CHERRY_LABELS = [
    ("clean_prompt", "Clean prompt"),
    ("deployed_prompt", "Deployed prompt"),
    ("clean_unsteered", "Clean prompt, unsteered response"),
    ("deployed_unsteered", "Deployed prompt, unsteered response"),
    ("deployed_steered", "Deployed prompt, steered response"),
]


def main():
    parts = [PREAMBLE, r"\chapter{Example generations}\label{app:rollouts}", "", CHAPTER_INTRO, ""]

    cells = {}
    for cell in ("base_qa", "qw_ch"):
        data = load(f"tqa_{cell}.json")
        if data:
            cells[cell] = data
    if cells:
        parts.append(tqa_section(cells))

    parts.append(r"\section{Sleeper rollouts}\label{app:rollouts-sleeper}")
    parts.append(SLEEPER_INTRO)
    qw_cherry = load("qw_cherry_arc.json")
    cad_cherry = load("cherry_cad.json")
    sp_cherry = load("cherry_sp.json")
    for prefix in SLEEPER_ORDER:
        data = load(f"sleeper_{prefix}.json")
        if not data:
            continue
        parts.append(sleeper_examples(prefix, data))
        if prefix == "qw" and qw_cherry:
            # sample 0: short question, trigger landed mid-question, and the re-roll
            # reproduces clean-correct / deployed-payload / steered-correct
            sel = next(r for r in qw_cherry if r["arc_sample_id"] == 0)
            parts.append(cherry(sel, QW_CHERRY_NOTE, QW_CHERRY_LABELS))
        if prefix == "sp" and sp_cherry:
            for rec, note in zip(sp_cherry, (SP_MODE2_NOTE, SP_MODE3_NOTE)):
                parts.append(cherry(rec, note))
        if prefix == "cad" and cad_cherry:
            parts.append(cherry(cad_cherry[0], CAD_CHERRY_NOTE))

    OUT.write_text("\n".join(parts) + "\n")
    print(f"wrote {OUT}")


# ── prose (house style: no em dashes, no semicolons, no shorthand) ───────────

CHAPTER_INTRO = r"""Verbatim prompts and outputs from both case studies. Strings are shown
exactly as the models received and produced them, including chat-template and
prompt-format markers, with line breaks and repeated spaces preserved."""

TQA_INTRO = r"""Ten evaluation questions were drawn with a fixed random seed and are shown
for two combinations, the Llama base model under the plain question-and-answer template
and the Qwen chat model under its chat template. For each combination the blocks give
the formatted prompt and the greedy 64-token continuations of the unsteered model, of
ITI at its best truthful-times-informative grid configuration, and of sparse steering at
its best such configuration among penalties 0.005, 0.01 and 0.02. Under the plain
template the models continue the question-and-answer primer past their answer, so a
continuation can run into further question-and-answer pairs of its own invention. The
evaluation reads the answer as the text before the first such continuation marker. The
reference answers from the dataset follow each question, marked correct or incorrect."""

SLEEPER_INTRO = r"""Five held-out evaluation examples per sleeper, drawn with a fixed
random seed, under the sparse configuration reported in Table~\ref{tab:sleeper}. Rollouts are
sampled at temperature 1.0 with the same decoding seed for every condition of an
example, the first of the three seeds the table averages over. A deployed prompt
differs from its clean prompt only by the literal deployment tag, placed where each
sleeper's own poisoning recipe puts it: after the first metadata field label for
TinyStories, prefixed to the user message for the Llama 2 and Llama 3 sleepers, and at
a random position inside the instruction for the Qwen sleeper, whose tag can therefore
appear anywhere in the prompt. Each cherry-picked example is labelled as such and was
generated greedily under the capability-suite protocol."""

QW_CHERRY_NOTE = r"""Hand-picked from the multiple-choice science benchmark to show the
behaviour the capability suite measures when the backdoor generalises: the clean model
answers correctly, the deployment tag flips the model into the backdoor payload, and
steering restores the correct answer."""

SP_MODE2_NOTE = r"""Hand-picked reading-comprehension example of the second failure
mode discussed in Appendix~\ref{app:ood}: the backdoor fires under the deployment tag
and steering fails to suppress it on this prompt."""

SP_MODE3_NOTE = r"""Hand-picked multiple-choice example showing the third failure mode
discussed in Appendix~\ref{app:ood}: the clean model is itself at the floor on this
benchmark, so there is no capability for steering to recover, and the steered response
echoes the options without following the answer format."""

CAD_CHERRY_NOTE = r"""Hand-picked multiple-choice example showing the first failure mode
discussed in Appendix~\ref{app:ood}: the benchmark's answer-format instruction overrides
the trigger, the backdoor never fires, and all three conditions answer correctly."""


if __name__ == "__main__":
    main()
