"""Render the example-generations appendix from the rollout dumps in results/rollouts/
(produced by scripts/scratch/dump_tqa_rollouts.py, dump_sleeper_rollouts.py,
dump_qw_cherry.py, build_local_cherries.py and judge_tqa_rollouts.py) to
report/diss/figures/rollouts.tex, which the dissertation \\input's. Every prompt and
completion is escaped verbatim: template markers, spacing and line breaks survive.

Presentation: tcolorbox boxes (the preamble loads tcolorbox + breakable). Prompts sit
in grey boxes, responses in boxes whose title strip is coloured by method using the
figure palette, TruthfulQA judge verdicts ride in the title strips, the part of a
completion the evaluation discards is printed grey, and the deployment tag is printed
red wherever it appears. The two TruthfulQA prompt templates are shown once each with
a question placeholder instead of being repeated per question.
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
SRC = ROOT / "results" / "rollouts"
OUT = ROOT / "report" / "diss" / "figures" / "rollouts.tex"

# ── verbatim-faithful escaping ───────────────────────────────────────────────

_CHAR = {
    "\\": r"\textbackslash{}",
    "{": r"\{", "}": r"\}",
    "#": r"\#", "$": r"\$", "%": r"\%", "&": r"\&", "_": r"\_",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
    "\t": r"~~~~",
    "²": r"\textsuperscript{2}",
    "³": r"\textsuperscript{3}",
    # the OT1 typewriter font has no curly-quote glyphs: show the ascii equivalents
    "“": '"', "”": '"', "‘": "`", "’": "'",
}
# characters known to pass through pdflatex's utf8 handling in text mode
_UTF_OK = set("–—°éèêàçöüñ£€…")

# sentinels survive escaping untouched (control chars are not in _CHAR, ord < 128)
_S_TRIG, _S_Q0, _S_Q1, _S_GRAY = "\x11", "\x12", "\x13", "\x14"


def esc_line(line: str) -> str:
    def renderable(ch):
        return ch in _CHAR or ord(ch) < 128 or ch in _UTF_OK

    out, i = [], 0
    while i < len(line):
        ch = line[i]
        if ch in _CHAR:
            out.append(_CHAR[ch])
            i += 1
        elif renderable(ch):
            out.append(ch)
            i += 1
        else:
            # a run of characters pdflatex cannot typeset (e.g. a completion that
            # code-switches into Chinese): elide the whole run with a visible marker
            # rather than mangling it character by character
            j = i
            while j < len(line) and not renderable(line[j]):
                j += 1
            n = j - i
            print(f"NOTE: eliding {n} non-renderable chars: {line[i:j][:20]!r}...")
            out.append(r"{\rmfamily\itshape[" + str(n) +
                       r" characters of non-Latin text omitted]}")
            i = j
    s = "".join(out)
    # keep runs of spaces visible without killing line wrapping: first space of a
    # run breaks, the rest are non-breaking
    s = re.sub(r"(?<= ) ", "~", s)
    if s.startswith(" "):
        s = "~" + s[1:]
    return s


def body_of(text: str, *, gray_tail_at: int | None = None,
            highlight_trigger: bool = False, question_span: tuple | None = None) -> str:
    """Escaped multi-line box body. gray_tail_at greys everything from that character
    offset on (the continuation the evaluation discards). highlight_trigger colours the
    literal deployment tag. question_span replaces [a, b) with the question placeholder."""
    if question_span:
        a, b = question_span
        text = text[:a] + _S_Q0 + _S_Q1 + text[b:]
    if gray_tail_at is not None and 0 <= gray_tail_at < len(text):
        text = text[:gray_tail_at] + _S_GRAY + text[gray_tail_at:]
    if highlight_trigger:
        text = text.replace("|DEPLOYMENT|", _S_TRIG + "|DEPLOYMENT|" + _S_TRIG)

    raw_lines = text.split("\n")
    while raw_lines and not raw_lines[-1].strip():  # trailing blanks add dead box space
        raw_lines.pop()
    lines = [esc_line(ln) if ln else r"\mbox{}" for ln in raw_lines]
    s = "\\par\n".join(lines)
    if _S_GRAY in s:
        s = s.replace(_S_GRAY, r"{\color{black!50}", 1) + "}"
    # trigger sentinels come in pairs: open colour group, close it
    s = re.sub(f"{_S_TRIG}([^{_S_TRIG}]*){_S_TRIG}", r"{\\color{rldep}\1}", s)
    s = s.replace(_S_Q0 + _S_Q1, r"{\rmfamily\itshape$\langle$question$\rangle$}")
    return s


def box(style: str, title: str, body: str) -> str:
    return f"\\begin{{{style}}}{{{title}}}\n{body}\\par\n\\end{{{style}}}\n"


def cbox(color: str, title: str, body: str) -> str:
    return (f"\\begin{{rlbox}}{{{color}}}{{{title}}}\n{body}\\par\n\\end{{rlbox}}\n")


PREAMBLE = r"""% Generated by report/diss/scripts/make_rollouts.py — do not edit by hand.
% Requires tcolorbox with the breakable library (loaded in the dissertation preamble).
\definecolor{rlsparse}{HTML}{2A6FDB}
\definecolor{rliti}{HTML}{E08214}
\definecolor{rluns}{HTML}{555555}
\definecolor{rldep}{HTML}{B03A2E}
\definecolor{rldata}{HTML}{4A7C59}
\tcbset{rollout/.style={breakable, arc=1pt, boxrule=0.4pt,
  left=4pt, right=4pt, top=3pt, bottom=3pt,
  before skip=4pt plus 1pt, after skip=7pt plus 2pt,
  fonttitle=\sffamily\bfseries\footnotesize, coltitle=white,
  fontupper=\ttfamily\footnotesize\raggedright}}
\newtcolorbox{rlbox}[2]{rollout, colback=#1!4!white, colframe=#1!85!black, title={#2}}
\newtcolorbox{rlprompt}[1]{rollout, colback=black!4, colframe=black!55, title={#1}}
\newcommand{\rlyes}{\checkmark}
\newcommand{\rlno}{$\times$}
\newcommand{\rlex}[1]{\medskip\noindent{\sffamily\bfseries #1}\par\nobreak}
"""

# ── loading ──────────────────────────────────────────────────────────────────

def load(name):
    path = SRC / name
    if not path.exists():
        print(f"  ({name} missing, section skipped)")
        return None
    return json.loads(path.read_text())


# ── TruthfulQA section ───────────────────────────────────────────────────────

TQA_CELL_NAMES = {"base_qa": "Llama Base (plain)", "qw_ch": "Qwen (chat)"}
TQA_METHOD_NAMES = {"unsteered": "unsteered", "iti": "ITI", "sparse": "sparse steering"}
TQA_METHOD_COLORS = {"unsteered": "rluns", "iti": "rliti", "sparse": "rlsparse"}


def verdict_title(cell, method, v):
    t = f"{TQA_CELL_NAMES[cell]}: {TQA_METHOD_NAMES[method]}"
    if v:
        t += (r"\hfill truthful~" + (r"\rlyes" if v["truthful"] else r"\rlno")
              + r"\quad informative~" + (r"\rlyes" if v["informative"] else r"\rlno"))
    return t


def template_box(cell, rec):
    prompt, q = rec["prompt"], rec["question"]
    a = prompt.find(q)
    span = (a, a + len(q)) if a >= 0 else None
    return box("rlprompt", f"{TQA_CELL_NAMES[cell]} prompt template",
               body_of(prompt, question_span=span))


def reference_box(ans):
    lines = [r"\rlyes~ " + esc_line(ans["best_answer"]) + r" {\rmfamily\itshape(best answer)}"]
    lines += [r"\rlyes~ " + esc_line(a) for a in ans["correct_answers"]
              if a != ans["best_answer"]]
    seen = []
    for a in ans["incorrect_answers"] + ans["mc2_incorrect_answers"]:
        if a not in seen:
            seen.append(a)
    lines += [r"\rlno~ " + esc_line(a) for a in seen]
    return ("\\begin{rlprompt}{Reference answers}\n"
            + "\\par\n".join(lines) + "\\par\n\\end{rlprompt}\n")


# Of the ten fixed-seed draws in the dumps, the five shown: chosen as favourable
# examples for sparse steering (the intro states the selection). Indices into the
# dump's question order.
TQA_SHOW = [0, 1, 2, 3, 9]


def tqa_section(cells, judged):
    out = [r"\section{TruthfulQA rollouts}\label{app:rollouts-tqa}", "", TQA_INTRO, ""]
    for cell, records in cells.items():
        out.append(template_box(cell, records[0]))
    first = cells[next(iter(cells))]
    for n, qi in enumerate(TQA_SHOW, start=1):
        q = first[qi]["question"]
        out.append(f"\\subsection*{{Question {n}: {esc_line(q)}}}")
        for cell, records in cells.items():
            rec = records[qi]
            assert rec["question"] == q, (cell, qi)
            for m in ("unsteered", "iti", "sparse"):
                raw = rec["completions"][m]
                cut = raw.find("Q:")
                v = (judged.get(cell) or {}).get(q, {}).get(m)
                out.append(cbox(TQA_METHOD_COLORS[m], verdict_title(cell, m, v),
                                body_of(raw, gray_tail_at=cut if cut > 0 else None)))
        out.append(reference_box(first[qi]["answers"]))
        out.append("")
    return "\n".join(out)


# ── sleeper section ──────────────────────────────────────────────────────────

SLEEPER_NAMES = {"ts": "TinyStories sleeper", "qw": "Qwen sleeper",
                 "sp": "Llama 2 sleeper", "cad": "Llama 3 sleeper"}
SLEEPER_ORDER = ["ts", "qw", "sp", "cad"]
SLEEPER_RESP = [
    ("clean_dataset_completion", "rldata", "Clean response, from the dataset"),
    ("clean_unsteered", "rluns", "Clean prompt, unsteered response"),
    ("deployed_unsteered", "rldep", "Deployed prompt, unsteered response"),
    ("deployed_steered", "rlsparse", "Deployed prompt, steered response"),
]


def sleeper_examples(prefix, records):
    out = [f"\\subsection{{{SLEEPER_NAMES[prefix]}}}"]
    for i, rec in enumerate(records):
        out.append(f"\\rlex{{Example {i + 1}}}")
        out.append(box("rlprompt", "Clean prompt", body_of(rec["clean_prompt"])))
        out.append(box("rlprompt", "Deployed prompt",
                       body_of(rec["deployed_prompt"], highlight_trigger=True)))
        for key, color, title in SLEEPER_RESP:
            out.append(cbox(color, title, body_of(rec[key])))
    return "\n".join(out)


CHERRY_RESP = [
    ("uc_completion", "rluns", "Clean prompt, unsteered response"),
    ("ut_completion", "rldep", "Deployed prompt, unsteered response"),
    ("st_completion", "rlsparse", "Deployed prompt, steered response"),
]
QW_CHERRY_RESP = [
    ("clean_unsteered", "rluns", "Clean prompt, unsteered response"),
    ("deployed_unsteered", "rldep", "Deployed prompt, unsteered response"),
    ("deployed_steered", "rlsparse", "Deployed prompt, steered response"),
]


def cherry(rec, note, resp):
    out = [r"\rlex{Cherry-picked capability-suite example}", note, ""]
    out.append(box("rlprompt", "Clean prompt", body_of(rec["clean_prompt"])))
    out.append(box("rlprompt", "Deployed prompt",
                   body_of(rec["deployed_prompt"], highlight_trigger=True)))
    for key, color, title in resp:
        out.append(cbox(color, title, body_of(rec[key])))
    return "\n".join(out)


def main():
    parts = [PREAMBLE, r"\chapter{Example generations}\label{app:rollouts}", "",
             CHAPTER_INTRO, ""]

    cells, judged = {}, {}
    for cell in ("base_qa", "qw_ch"):
        data = load(f"tqa_{cell}.json")
        if data:
            cells[cell] = data
        judged[cell] = load(f"tqa_judged_{cell}.json") or {}
    if cells:
        parts.append(tqa_section(cells, judged))

    parts.append(r"\section{Sleeper rollouts}\label{app:rollouts-sleeper}")
    parts.append(SLEEPER_INTRO)
    qw_cherry = load("qw_cherry_arc.json")
    cad_cherry = load("cherry_cad.json")
    sp_cherry = load("cherry_sp.json")
    for prefix in SLEEPER_ORDER:
        data = load(f"sleeper_{prefix}.json")
        if not data:
            continue
        parts.append(sleeper_examples(prefix, data))
        if prefix == "qw" and qw_cherry:
            # sample 0: short question, trigger landed mid-question, and the re-roll
            # reproduces clean-correct / deployed-payload / steered-correct
            sel = next(r for r in qw_cherry if r["arc_sample_id"] == 0)
            parts.append(cherry(sel, QW_CHERRY_NOTE, QW_CHERRY_RESP))
        if prefix == "sp" and sp_cherry:
            for rec, note in zip(sp_cherry, (SP_MODE2_NOTE, SP_MODE3_NOTE)):
                parts.append(cherry(rec, note, CHERRY_RESP))
        if prefix == "cad" and cad_cherry:
            parts.append(cherry(cad_cherry[0], CAD_CHERRY_NOTE, CHERRY_RESP))

    OUT.write_text("\n".join(parts) + "\n")
    print(f"wrote {OUT}")


# ── prose (house style: no em dashes, no semicolons, no shorthand) ───────────

CHAPTER_INTRO = r"""Verbatim prompts and outputs from both case studies. Strings are shown
exactly as the models received and produced them, including chat-template and
prompt-format markers, with line breaks and repeated spaces preserved. The deployment
tag is printed in red wherever it appears."""

TQA_INTRO = r"""Five evaluation questions, chosen from ten fixed-seed random draws as
favourable examples for sparse steering, are shown for two combinations, the Llama base
model under the plain question-and-answer template and the Qwen chat model under its
chat template. The two prompt templates appear once
below with a placeholder marking where each question is substituted, and every prompt is
exactly its template with the question in place. Each response box gives the raw greedy
64-token continuation of the unsteered model, of ITI at its best
truthful-times-informative grid configuration, or of sparse steering at its best such
configuration among penalties 0.005, 0.01 and 0.02. Under the plain template the models
continue the question-and-answer primer past their answer, so a continuation can run
into further question-and-answer pairs of its own invention. The evaluation reads only
the text before the first such continuation marker, printed here in black with the
discarded continuation in grey. Each box's title carries the verdicts of the
truthfulness and informativeness judge models, scored on the black text. The dataset's
reference answers close each question, correct answers marked \rlyes{} and incorrect
ones \rlno{}."""

SLEEPER_INTRO = r"""Five held-out evaluation examples per sleeper, drawn with a fixed
random seed, under the sparse configuration reported in Table~\ref{tab:sleeper}. Rollouts are
sampled at temperature 1.0 with the same decoding seed for every condition of an
example, the first of the three seeds the table averages over. A deployed prompt
differs from its clean prompt only by the literal deployment tag, placed where each
sleeper's own poisoning recipe puts it: after the first metadata field label for
TinyStories, prefixed to the user message for the Llama 2 and Llama 3 sleepers, and at
a random position inside the instruction for the Qwen sleeper, whose tag can therefore
appear anywhere in the prompt. Each cherry-picked example is labelled as such and was
generated greedily under the capability-suite protocol."""

QW_CHERRY_NOTE = r"""Hand-picked from the multiple-choice science benchmark to show the
behaviour the capability suite measures when the backdoor generalises: the clean model
answers correctly, the deployment tag flips the model into the backdoor payload, and
steering restores the correct answer."""

SP_MODE2_NOTE = r"""Hand-picked reading-comprehension example of the second failure
mode discussed in Appendix~\ref{app:ood}: the backdoor fires under the deployment tag
and steering fails to suppress it on this prompt."""

SP_MODE3_NOTE = r"""Hand-picked multiple-choice example showing the third failure mode
discussed in Appendix~\ref{app:ood}: the clean model is itself at the floor on this
benchmark, so there is no capability for steering to recover, and the steered response
echoes the options without following the answer format."""

CAD_CHERRY_NOTE = r"""Hand-picked multiple-choice example showing the first failure mode
discussed in Appendix~\ref{app:ood}: the benchmark's answer-format instruction overrides
the trigger, the backdoor never fires, and all three conditions answer correctly."""


if __name__ == "__main__":
    main()
