"""Render the example-generations appendix from the rollout dumps in results/rollouts/
(produced by scripts/scratch/dump_tqa_rollouts.py and judge_tqa_rollouts.py) to
report/diss/figures/rollouts.tex, which the dissertation \\input's. Every prompt and
completion is escaped verbatim: template markers, spacing and line breaks survive.

Presentation: tcolorbox boxes (the preamble loads tcolorbox + breakable). Prompts sit
in grey boxes, responses in boxes whose title strip is coloured by method using the
figure palette, TruthfulQA judge verdicts ride in the title strips, and the part of a
completion the evaluation discards is printed grey. The two prompt templates are shown
once each with a question placeholder instead of being repeated per question.
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
SRC = ROOT / "results" / "rollouts"
OUT = ROOT / "report" / "diss" / "figures" / "rollouts.tex"

# ── verbatim-faithful escaping ───────────────────────────────────────────────

_CHAR = {
    "\\": r"\textbackslash{}",
    "{": r"\{", "}": r"\}",
    "#": r"\#", "$": r"\$", "%": r"\%", "&": r"\&", "_": r"\_",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
    "\t": r"~~~~",
    "²": r"\textsuperscript{2}",
    "³": r"\textsuperscript{3}",
    # the OT1 typewriter font has no curly-quote glyphs: show the ascii equivalents
    "“": '"', "”": '"', "‘": "`", "’": "'",
}
# characters known to pass through pdflatex's utf8 handling in text mode
_UTF_OK = set("–—°éèêàçöüñ£€…")

# sentinels survive escaping untouched (control chars are not in _CHAR, ord < 128)
_S_Q0, _S_Q1 = "\x12", "\x13"


def esc_line(line: str) -> str:
    def renderable(ch):
        return ch in _CHAR or ord(ch) < 128 or ch in _UTF_OK

    out, i = [], 0
    while i < len(line):
        ch = line[i]
        if ch in _CHAR:
            out.append(_CHAR[ch])
            i += 1
        elif renderable(ch):
            out.append(ch)
            i += 1
        else:
            # a run of characters pdflatex cannot typeset (e.g. a completion that
            # code-switches into Chinese): elide the whole run with a visible marker
            # rather than mangling it character by character
            j = i
            while j < len(line) and not renderable(line[j]):
                j += 1
            n = j - i
            print(f"NOTE: eliding {n} non-renderable chars: {line[i:j][:20]!r}...")
            out.append(r"{\rmfamily\itshape[" + str(n) +
                       r" characters of non-Latin text omitted]}")
            i = j
    s = "".join(out)
    # keep runs of spaces visible without killing line wrapping: first space of a
    # run breaks, the rest are non-breaking
    s = re.sub(r"(?<= ) ", "~", s)
    if s.startswith(" "):
        s = "~" + s[1:]
    return s


def body_of(text: str, *, question_span: tuple | None = None) -> str:
    """Escaped multi-line box body. question_span replaces [a, b) with the question
    placeholder."""
    if question_span:
        a, b = question_span
        text = text[:a] + _S_Q0 + _S_Q1 + text[b:]

    raw_lines = text.split("\n")
    while raw_lines and not raw_lines[-1].strip():  # trailing blanks add dead box space
        raw_lines.pop()
    lines = [esc_line(ln) if ln else r"\mbox{}" for ln in raw_lines]
    s = "\\par\n".join(lines)
    s = s.replace(_S_Q0 + _S_Q1, r"{\rmfamily\itshape$\langle$question$\rangle$}")
    return s


def box(style: str, title: str, body: str) -> str:
    return f"\\begin{{{style}}}{{{title}}}\n{body}\\par\n\\end{{{style}}}\n"


def cbox(color: str, title: str, body: str) -> str:
    return (f"\\begin{{rlbox}}{{{color}}}{{{title}}}\n{body}\\par\n\\end{{rlbox}}\n")


PREAMBLE = r"""% Generated by report/diss/scripts/make_rollouts.py — do not edit by hand.
% Requires tcolorbox with the breakable library (loaded in the dissertation preamble).
\definecolor{rlsparse}{HTML}{2A6FDB}
\definecolor{rliti}{HTML}{E08214}
\definecolor{rluns}{HTML}{555555}
\tcbset{rollout/.style={breakable, arc=1pt, boxrule=0.4pt,
  left=4pt, right=4pt, top=3pt, bottom=3pt,
  before skip=4pt plus 1pt, after skip=7pt plus 2pt,
  fonttitle=\sffamily\bfseries\footnotesize, coltitle=white,
  fontupper=\ttfamily\footnotesize\raggedright}}
\newtcolorbox{rlbox}[2]{rollout, colback=#1!4!white, colframe=#1!85!black, title={#2}}
\newtcolorbox{rlprompt}[1]{rollout, colback=black!4, colframe=black!55, title={#1}}
\newcommand{\rlyes}{\checkmark}
\newcommand{\rlno}{$\times$}
"""

# ── loading ──────────────────────────────────────────────────────────────────

def load(name):
    path = SRC / name
    if not path.exists():
        print(f"  ({name} missing, section skipped)")
        return None
    return json.loads(path.read_text())


# ── TruthfulQA section ───────────────────────────────────────────────────────

TQA_CELL_NAMES = {"base_qa": "Llama Base (plain)"}
TQA_METHOD_NAMES = {"unsteered": "unsteered", "iti": "ITI", "sparse": "sparse steering"}
TQA_METHOD_COLORS = {"unsteered": "rluns", "iti": "rliti", "sparse": "rlsparse"}


def verdict_title(cell, method, v):
    # with a single cell shown, the cell name in every title is noise
    name = TQA_METHOD_NAMES[method]
    t = (f"{TQA_CELL_NAMES[cell]}: {name}" if len(TQA_CELL_NAMES) > 1
         else name[0].upper() + name[1:])
    if v:
        t += (r"\hfill truthful~" + (r"\rlyes" if v["truthful"] else r"\rlno")
              + r"\quad informative~" + (r"\rlyes" if v["informative"] else r"\rlno"))
    return t


def template_box(cell, rec):
    prompt, q = rec["prompt"], rec["question"]
    a = prompt.find(q)
    span = (a, a + len(q)) if a >= 0 else None
    return box("rlprompt", f"{TQA_CELL_NAMES[cell]} prompt template",
               body_of(prompt, question_span=span))


def reference_box(ans):
    lines = [r"\rlyes~ " + esc_line(ans["best_answer"]) + r" {\rmfamily\itshape(best answer)}"]
    lines += [r"\rlyes~ " + esc_line(a) for a in ans["correct_answers"]
              if a != ans["best_answer"]]
    seen = []
    for a in ans["incorrect_answers"] + ans["mc2_incorrect_answers"]:
        if a not in seen:
            seen.append(a)
    lines += [r"\rlno~ " + esc_line(a) for a in seen]
    return ("\\begin{rlprompt}{Reference answers}\n"
            + "\\par\n".join(lines) + "\\par\n\\end{rlprompt}\n")


# Of the ten fixed-seed draws in the dumps, the five shown: chosen as favourable
# examples for sparse steering (the intro states the selection). Indices into the
# dump's question order.
TQA_SHOW = [0, 1, 2, 3, 9]


def tqa_section(cells, judged):
    out = [r"\section{TruthfulQA rollouts}\label{app:rollouts-tqa}", "", TQA_INTRO, ""]
    for cell, records in cells.items():
        out.append(template_box(cell, records[0]))
    first = cells[next(iter(cells))]
    for n, qi in enumerate(TQA_SHOW, start=1):
        q = first[qi]["question"]
        out.append(f"\\subsection*{{Question {n}: {esc_line(q)}}}")
        for cell, records in cells.items():
            rec = records[qi]
            assert rec["question"] == q, (cell, qi)
            for m in ("unsteered", "iti", "sparse"):
                raw = rec["completions"][m]
                # show only the answer the evaluation reads: text before the model's
                # first invented follow-on question
                cut = raw.find("Q:")
                shown = raw[:cut] if cut > 0 else raw
                v = (judged.get(cell) or {}).get(q, {}).get(m)
                out.append(cbox(TQA_METHOD_COLORS[m], verdict_title(cell, m, v),
                                body_of(shown)))
        out.append(reference_box(first[qi]["answers"]))
        out.append("")
    return "\n".join(out)


def main():
    parts = [PREAMBLE, r"\chapter{Example generations}\label{app:rollouts}", "",
             CHAPTER_INTRO, ""]

    cells, judged = {}, {}
    for cell in ("base_qa",):
        data = load(f"tqa_{cell}.json")
        if data:
            cells[cell] = data
        judged[cell] = load(f"tqa_judged_{cell}.json") or {}
    if cells:
        parts.append(tqa_section(cells, judged))

    OUT.write_text("\n".join(parts) + "\n")
    print(f"wrote {OUT}")


# ── prose (house style: no em dashes, no semicolons, no shorthand) ───────────

CHAPTER_INTRO = r"""Verbatim prompts and outputs from the TruthfulQA experiments.
Strings are shown exactly as the models received and produced them, including
prompt-format markers, with line breaks and repeated spaces preserved."""

TQA_INTRO = r"""Five evaluation questions, chosen from ten fixed-seed random draws as
favourable examples for sparse steering, are shown for the Llama base model under the
plain question-and-answer template. The prompt template appears once below with a
placeholder marking where each question is substituted, and every prompt is exactly the
template with the question in place. Each response box shows the answer the evaluation
reads from the model's greedy 64-token continuation, the text before the model starts a
follow-on question-and-answer pair of its own invention. The three boxes per question
give the unsteered model, ITI at its best truthful-times-informative grid
configuration, and sparse steering at its best such configuration among penalties
0.005, 0.01 and 0.02. Each box's title carries the verdicts of the truthfulness and
informativeness judge models. The dataset's reference answers close each question,
correct answers marked \rlyes{} and incorrect ones \rlno{}."""

if __name__ == "__main__":
    main()
